#!/bin/bash
#--
#
# Purpose: handles student missions on matrix
# Creator: Mark Fernandes.
# Created: March 25, 2020
# Updated: March 25, 2020
# License: MIT

OWNER=mark.fernandes
RIDER=20a

DIR=/home/${OWNER}/.${RIDER}
TIMESTAMP=$(/usr/bin/date +"%Y%m%d_%H:%M%S")

logF=${DIR}/${USER}-${TIMESTAMP}

touch ${logF}
chmod 660 $logF

# content of test goes here
echo "What is your name?" >> $logF

echo "What editior do you want to edit with? "
echo "Your choices are: "
echo "n(a)no"
echo "(e)macs"
echo "(n)led"
echo "(v)im"
read -p  "Your choice: " myeditor

case $myeditor in
    a) /usr/bin/nano $logF ;;
    e) /usr/bin/emacs $logF ;;
    n) /usr/local/bin/nled $logF ;;
    v) /usr/bin/vim $logF ;;
    *) { echo "No such editor" 2>&1 ; exit ; } ;;
esac

echo

if [[ $? -eq 0 && -s $logF ]];
then
    chmod 060 $logF
    [[ $? -eq 0 ]] && { echo "Congratulations!! You submission was successful" ; exit ; }
fi

echo "Did not work, contact your teacher"
