#!/bin/bash
#--
#
# Purpose: used on matrix to get student work
# Creator: Mark Fernandes.
# Updated: March 25, 2020
# License: MIT

TEACHER=mark.fernandes
SEMESTR=20a

DIR=/home/${TEACHER}/.${SEMESTER}
TIMESTAMP=$(/usr/bin/date +"%Y%m%d_%H:%M%S")

logF=${DIR}/${USER}-${TIMESTAMP}

touch ${logF}
chmod 660 $logF

# content of test goes here
echo "What is your name?" >> $logF

echo "What editior do you want to edit with? " 
echo "Your choices are: " 
echo "1. vi"
echo "2. nano"
echo "3. emacs"
read -p  "Your choice [1-3]: " myeditor

case $myeditor in
    1) /usr/bin/vi $logF ;;
    2) /usr/bin/nano $logF ;;
    3) /usr/bin/emacs $logF ;;
    *) { echo No such editor 2&>1 ; exit ; } ;;
esac

echo

if [[ $? -eq 0 && -s $logF ]];
then
    chmod 060 $logF
    [[ $? -eq 0 ]] && { echo "Congratulations!! You submission was successful" ; exit ; }
fi

echo "Did not work, contact your teacher"
