#!/bin/bash

FILE=$1

INPUT=""
TNAME="ABCD"
TLEAD=""

trap "" EXIT

if [ ! -s "${FILE}" ]; then
  echo "No sections found."
  exit 1
fi

header() {

  s=${1:--}

  for c in $(seq 1 $((COLUMNS - 10)))
  do
    echo -n "$s"
  done
  echo
}

show_section() {
  clear

  header
  sed '/#/d;/^$/d' "${1}" | awk -F'|' '{print $1, $2}'| column
  header
  echo -n "Which 3 letter code above represents your section? "

}

read_input() {
  read INPUT
  INPUT=$(echo "${INPUT}" | tr -cd "[:print:]\n"  | tr '[a-z]' '[A-Z]'| sed 's/ //g')
  TNAME=$(grep -wR "${INPUT}" ${FILE} 2>/dev/null | cut -d'|' -f1)
  TLEAD=$(grep -wR "${INPUT}" ${FILE} 2>/dev/null | cut -d'|' -f3)
}

check_input() {
  if [ -z "${INPUT}" ] || [ "${TNAME}" != "${INPUT}" ]; then
    echo -ne "\nInvalid section. Press any key to try again."
    read
  fi
}

show_section "${FILE}"
read_input
check_input "${INPUT}"


if [ -z "${INPUT}" ] || [ -z "${TNAME}" ] || [[ "${TNAME}" != "${INPUT}" ]];
then
  echo  "${0}" "${1}"
else
  clear
  >&2 echo -n "$TNAME,$TLEAD"
fi
