#!/bin/bash

SCR=$0
#          $1        $2       $3            $4        $5            $6      $7         $8
# shMail + subject + adminF + player.Name + preTeam + player.Team + score + subjPost + doneF
SUBJ=$1
ADMN=$2

FROM=$3
PRFX=$4
TEAM=$5
DONE=$6
POST=$7
BODY=$8

LN=$(grep -w "${TEAM}" "${ADMN}")
TO=$(echo "${LN}" | cut -d'|' -f4)
YN=$(echo "${LN}" | cut -d'|' -f5 | tr '[A-Z]' '[a-z]')

if [ ! -s "${BODY}" ]; then
  echo "Invalid message content: ${BODY}"
  exit 1
fi

if [[ "${YN}" == "yes" ]]; then
  tac "${BODY}" |\
  awk -F, '(NR == 1){print "Completed level",$6,"in",$7,". Total",$5,"done.\n\n# date,user,team,lead,score,level,time"};{print}' |\
  mail -s "${PRFX}${TEAM} ${SUBJ} ${DONE} ${POST}" -S replyto="${FROM}" "${TO}" 2>/dev/null
fi
