#!/bin/bash

SCR=$0
#          $1        $2       $3            $4            $5      $6
# shMail + subject + adminF + player.Name + player.Team + score + doneF
SUBJ=$1
ADMN=$2

FROM=$3
TEAM=$4
DONE=$5
BODY=$6

LN=$(grep -w "${TEAM}" "${ADMN}")
TO=$(echo "${LN}"| cut -d'|' -f4)
YN=$(echo "${LN}"| cut -d'|' -f5| tr '[A-Z]' '[a-z]')

if [ ! -s "${BODY}" ]; then
  echo "Invalid message content: ${BODY}"
  exit 1
fi

if [[ "${YN}" == "yes" ]]; then
  tac "${BODY}" | mail -s "${SUBJ}${TEAM} ${DONE}" -S replyto="${FROM}" "${TO}" 2>/dev/null
fi
