#!/bin/bash

SCR=$0

DFILE=$1
FIELD=6
SCORE=

if [ ! -s "${DFILE}" ]; then
  >&2 echo "Directory not found. ${DFILE}"
  exit 1
fi

SCORE=$(sort -ut, -nk"${FIELD}","${FIELD}" "${DFILE}" | cut -d, -f"${FIELD}" | tr '\n' ',' | sed 's/,$//')

echo -n ${SCORE}
