#!/bin/bash

SCR=$0

DONEF=$1
SCORE=

if [ ! -s "${DONEF}" ]; then
  >&2 echo "File empty or not found: ${DONEF}"
  exit 1
fi

SCORE=$(sort -ut, -nk6,6 "${DONEF}" | cut -d, -f6 | tr '\n' ',' | sed 's/,$//')

echo -n ${SCORE}
